### ISSUE TITLE
Remove Non-Functioning Buttons from Tree Structure Example

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-design-patterns#162]
#### Describe the desired behavior
In the demo, these buttons were brought up as a potentially confusing to end-users since they don't do anything in the demo. 
Potentially remove these "New Folder" and "Delete" buttons.   Alternatively, add functionality to them. 

![image](https://user-images.githubusercontent.com/6538289/142037236-0d4ac9a1-037b-4212-aad1-d1c1809e0457.png)

#### Describe the current behavior
Buttons do not do anything. 

#### Is this request related to a current issue?
No

**Comment by ektasawant** [comment]
Remove "New Folder" and "Delete" buttons.
