### ISSUE TITLE
Dropdown Toolbar doesn't work on mobile

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-design-patterns#179]
#### Describe the bug

In https://stackblitz.com/github/brightlayer-ui/angular-design-patterns/tree/dev, the dropdown toolbar doesn't work. (This haven't been checked locally yet)

It throws the following error

> ERROR Error: No component factory found for DropdownToolbarBottomSheetExample. Did you add it to @NgModule.entryComponents?

Desktop width seems to work fine

#### What is the expected behavior?

Should work on mobile

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/8997218/149554505-03285478-d3c6-44ca-89c9-c8a774ba2be1.mov
		
#### Anything else to add?
Discovered in #178

**Comment by emclaug2** [comment]
This has been fixed in #180
