### ISSUE TITLE
Overlay modal window not working in mobile view

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/angular-design-patterns#181]
#### Describe the bug
In https://stackblitz.com/github/brightlayer-ui/angular-design-patterns/tree/dev?file=src%2Fapp%2Fpages%2Fapp-bar%2Fdropdown-toolbar%2Fdropdown-toolbar.module.ts
when selecting the delete button while in mobile view, the modal does not display and throws error.

![image](https://user-images.githubusercontent.com/37150565/149562592-5a3a60b2-51af-40f6-a075-94d3c6f753c0.png)

#### What is the expected behavior?
should work in mobile view both locally and stackblitz
#### What are the steps to reproduce?
1. Go to... https://stackblitz.com/github/brightlayer-ui/angular-design-patterns/tree/dev?file=src%2Fapp%2Fpages%2Fapp-bar%2Fdropdown-toolbar%2Fdropdown-toolbar.module.ts
2. Navigate to 
![image](https://user-images.githubusercontent.com/37150565/149562753-cbbc2248-8551-47f0-b8b3-db56cb277100.png)

3. select delete button in example

**Comment by emclaug2** [comment]
Our angular design patterns aren't working in stackblitz anymore.
https://stackblitz.com/github/brightlayer-ui/angular-design-patterns/tree/dev?file=src%2Fapp%2Fpages%2Fapp-bar%2Fdropdown-toolbar%2Fdropdown-toolbar.module.ts


```
Error in turbo_modules/@brightlayer-ui/angular-themes@6.3.0/theme.scss
NoSuchMethodError: method not found: 'write$1' on null
```

**Comment by ektasawant** [comment]
<img width="718" alt="Screenshot 2022-04-05 at 3 34 53 PM" src="https://user-images.githubusercontent.com/10433274/161730774-00f7d739-56cd-4d82-b020-b2891b0109f9.png">
stackblitz link is working fine with no error https://aonivamwr--github--4200.local.webcontainer.io/lists/in-button-panel

**Comment by jeffvg** [comment]
verified this works now..

![image](https://user-images.githubusercontent.com/37150565/161970127-da77d158-4508-4bec-b8be-244a05dea106.png)
