### ISSUE TITLE
Tree structure folder icons should be gray[500]

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/angular-design-patterns#183]
#### Describe the bug
Tree structure folder icons are black[500]

#### What is the expected behavior?
Tree structure folder icons should be gray[500]

#### What are the steps to reproduce?
1. start design patterns project and navigate to the Lists/Tree Structure example
2. inspect folder icon and observe that it is the wrong color

#### Screenshots or links to minimum reproduction example
![Screen Shot 2022-01-14 at 1 31 06 PM](https://user-images.githubusercontent.com/13989985/149567207-242b1aac-b7b3-4185-b505-0a7e670a6115.png)

**Comment by emclaug2** [comment]
Fixed in #244
