### ISSUE TITLE
Tree structure selected radio buttons should be blue[500]

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/angular-design-patterns#184]
#### Describe the bug
Tree structure selected radio buttons are lightBlue[500]
#### What is the expected behavior?
Tree structure selected radio buttons should be blue[500]
#### What are the steps to reproduce?
1. start design patterns project and navigate to the Lists/Tree Structure example
2. select any item by clicking on the radio button
3. inspect radio button and observe that it is the wrong color

#### Screenshots or links to minimum reproduction example

![Screen Shot 2022-01-14 at 1 35 15 PM](https://user-images.githubusercontent.com/13989985/149567722-6e1b5bf1-bd87-4a61-a19a-3a34b9c944d4.png)

**Comment by emclaug2** [comment]
Doublecheck angular & react design pattern examples to see which one needs updated.

**Comment by emclaug2** [comment]
Fixed in #244
