### ISSUE TITLE
Should Run in CodeSandBox

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/angular-design-patterns#27]
#### Describe the bug
Code does not run in CodeSandBox

#### What is the expected behavior?
It should run when imported into CodeSandBox

#### What are the steps to reproduce?
Go here: 
https://codesandbox.io/s/github/pxblue/angular-design-patterns/tree/dev

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/88053992-a70e0400-cb2a-11ea-899e-ce627ae1e20a.png)

**Comment by emclaug2** [comment]
https://github.com/codesandbox/codesandbox-client/issues/2634

**Comment by emclaug2** [comment]
It looks like there might be a workaround in the thread linked above.

**Comment by emclaug2** [comment]
If the work around doesn't work, remove high priority label.

**Comment by huayunh** [comment]
I tried adding that `import 'core-js/proposals/reflect-metadata';` line to main.ts, but it is giving me the same error.

However, I also noticed that if you just fork the original dev branch (open any file and press `command`+`s`), you will get a working copy, with all your code absolutely the same as that from the original. I checked the dependencies too, and the dev branch and the forked one share the same versions.

**Comment by emclaug2** [comment]
I took a look at this with no luck; the error message that CodeSandbox is providing is not very helpful.

**Comment by emclaug2** [comment]
Considering this issue has been around for 2.5 years & we've started hosting this via firebase [here](https://blui-angular-design-patterns.web.app/). 
We also talked to our adopters and saw limited utility added by adding live-editing features for this project.

Closing this issue.
